
package Presentacion;

import Controlador.Media;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.border.Border;

public final class JFrmMain extends javax.swing.JFrame {

    public InputStream foto1=this.getClass().getResourceAsStream(File.separator+"Img"+File.separator+"Main.png");
    
    public JFrmMain() {
        initComponents();
        cargarImagen( jDPMain,foto1);
        this.setExtendedState(JFrmMain.MAXIMIZED_BOTH);
    }

    public  void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen)
    {   
        System.out.println(fileImagen);
        try{   
            BufferedImage image = ImageIO.read(fileImagen);        
            jDeskp.setBorder((Border) new Media(image));
        }
        catch (Exception e){   
            System.out.println("Imagen no disponible: "+e);   
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDPMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuFolios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuRecepcionCompras = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuMermas = new javax.swing.JMenu();
        jMenuRegistroMermas = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenProductos = new javax.swing.JMenu();
        jMenuProductos = new javax.swing.JMenuItem();
        jMenuDepartamentos = new javax.swing.JMenuItem();
        jMenCambioPrecios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuarios = new javax.swing.JMenuItem();
        jMenuPerfiles = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuProveedores = new javax.swing.JMenuItem();
        jMenSalirSistema = new javax.swing.JMenu();
        jMenSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPMainLayout = new javax.swing.GroupLayout(jDPMain);
        jDPMain.setLayout(jDPMainLayout);
        jDPMainLayout.setHorizontalGroup(
            jDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jDPMainLayout.setVerticalGroup(
            jDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMenu1.setText("Venta");

        jMenuItem5.setText("Ventas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuFolios.setText("Folios");
        jMenuFolios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFoliosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFolios);
        jMenu1.add(jSeparator2);

        jMenu6.setText("Informes");

        jMenuItem8.setText("Ventas por clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Ventas por productos");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("Ventas por fechas");
        jMenu6.add(jMenuItem10);

        jMenuItem12.setText("Ventas por horas");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Ventas por departamentos");
        jMenu6.add(jMenuItem13);
        jMenu6.add(jSeparator3);

        jMenuItem11.setText("Ranking productos");
        jMenu6.add(jMenuItem11);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenuRecepcionCompras.setText("Compra");

        jMenuItem16.setText("Recepción compras");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenuRecepcionCompras.add(jMenuItem16);
        jMenuRecepcionCompras.add(jSeparator5);

        jMenu7.setText("Informes");

        jMenuItem18.setText("Compras por proveedores");
        jMenu7.add(jMenuItem18);

        jMenuItem17.setText("Compras por productos");
        jMenu7.add(jMenuItem17);

        jMenuItem19.setText("compras por fecha");
        jMenu7.add(jMenuItem19);

        jMenuRecepcionCompras.add(jMenu7);

        jMenuBar1.add(jMenuRecepcionCompras);

        jMenuMermas.setText("Inventario");

        jMenuRegistroMermas.setText("Mermas");

        jMenuItem20.setText("Registro mermas");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenuRegistroMermas.add(jMenuItem20);

        jMenuItem21.setText("Informe de mermas");
        jMenuRegistroMermas.add(jMenuItem21);

        jMenuMermas.add(jMenuRegistroMermas);
        jMenuMermas.add(jSeparator6);

        jMenuItem22.setText("Planilla de inventario");
        jMenuMermas.add(jMenuItem22);

        jMenuItem23.setText("Tomas de inventario");
        jMenuMermas.add(jMenuItem23);

        jMenuItem24.setText("Consolidado de tomas de inventario");
        jMenuMermas.add(jMenuItem24);

        jMenuItem25.setText("Ajuste de inventario");
        jMenuMermas.add(jMenuItem25);
        jMenuMermas.add(jSeparator7);

        jMenu9.setText("Informes");

        jMenuItem26.setText("Informe de inventarios");
        jMenu9.add(jMenuItem26);

        jMenuItem27.setText("Kardex de un producto");
        jMenu9.add(jMenuItem27);

        jMenuItem28.setText("Inventario Valorizado");
        jMenu9.add(jMenuItem28);

        jMenuItem29.setText("Inventario por departamento");
        jMenu9.add(jMenuItem29);

        jMenuMermas.add(jMenu9);

        jMenuBar1.add(jMenuMermas);

        jMenProductos.setText("Maestro");

        jMenuProductos.setText("Productos");
        jMenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductosActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuProductos);

        jMenuDepartamentos.setText("Departamentos");
        jMenuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepartamentosActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuDepartamentos);

        jMenCambioPrecios.setText("Cambio de precios");
        jMenCambioPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenCambioPreciosActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenCambioPrecios);
        jMenProductos.add(jSeparator1);

        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuUsuarios);

        jMenuPerfiles.setText("Perfiles");
        jMenuPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPerfilesActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuPerfiles);
        jMenProductos.add(jSeparator4);

        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuClientes);

        jMenuProveedores.setText("Proveedores");
        jMenuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedoresActionPerformed(evt);
            }
        });
        jMenProductos.add(jMenuProveedores);

        jMenuBar1.add(jMenProductos);

        jMenSalirSistema.setText("Salir");

        jMenSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenSalir.setText("Salir del sistema");
        jMenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenSalirActionPerformed(evt);
            }
        });
        jMenSalirSistema.add(jMenSalir);

        jMenuBar1.add(jMenSalirSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductosActionPerformed
        // TODO add your handling code here:
        try {
            JIFProductos objPro = new JIFProductos();
            JFrmMain.jDPMain.add(objPro);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objPro.getSize(); 
            objPro.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objPro.toFront();
            objPro.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jMenuProductosActionPerformed

    private void jMenuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepartamentosActionPerformed
        // TODO add your handling code here:
        try {
            JIFDepartamentos jiDepartamentos = new JIFDepartamentos();
            JFrmMain.jDPMain.add(jiDepartamentos);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = jiDepartamentos.getSize(); 
            jiDepartamentos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            jiDepartamentos.toFront();
            jiDepartamentos.setVisible(true);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuDepartamentosActionPerformed

    private void jMenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenSalirActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPerfilesActionPerformed
        // TODO add your handling code here:
        try {
            JIFPerfiles jiPerfiles = new JIFPerfiles();
            JFrmMain.jDPMain.add(jiPerfiles);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = jiPerfiles.getSize(); 
            jiPerfiles.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            jiPerfiles.toFront();
            jiPerfiles.setVisible(true);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuPerfilesActionPerformed

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            JIFUsuarios objUsu =new JIFUsuarios();
            JFrmMain.jDPMain.add(objUsu);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objUsu.getSize(); 
            objUsu.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objUsu.toFront();
            objUsu.setVisible(true);    
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
        // TODO add your handling code here:
        try {
            JIFClientes objCli =new JIFClientes();
            JFrmMain.jDPMain.add(objCli);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objCli.getSize(); 
            objCli.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objCli.toFront();
            objCli.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedoresActionPerformed
        // TODO add your handling code here:
        try {
            JIFProveedores objPro =new JIFProveedores();
            JFrmMain.jDPMain.add(objPro);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objPro.getSize(); 
            objPro.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objPro.toFront();
            objPro.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuProveedoresActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        try {
            JIFMermas objMer =new JIFMermas();
            JFrmMain.jDPMain.add(objMer);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objMer.getSize(); 
            objMer.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objMer.toFront();
            objMer.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenCambioPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenCambioPreciosActionPerformed
        try {
            JIFCambioPrecio objCP =new JIFCambioPrecio();
            JFrmMain.jDPMain.add(objCP);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objCP.getSize(); 
            objCP.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objCP.toFront();
            objCP.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jMenCambioPreciosActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        try {
            JIFCompras objCom =new JIFCompras();
            JFrmMain.jDPMain.add(objCom);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objCom.getSize(); 
            objCom.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objCom.toFront();
            objCom.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            JIFVenta objVen =new JIFVenta();
            JFrmMain.jDPMain.add(objVen);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objVen.getSize(); 
            objVen.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objVen.toFront();
            objVen.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuFoliosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFoliosActionPerformed
        try {
            JIFFolios objFol =new JIFFolios();
            JFrmMain.jDPMain.add(objFol);
            Dimension desktopSize = JFrmMain.jDPMain.getSize();
            Dimension FrameSize = objFol.getSize(); 
            objFol.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            objFol.toFront();
            objFol.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuFoliosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDPMain;
    private javax.swing.JMenuItem jMenCambioPrecios;
    private javax.swing.JMenu jMenProductos;
    private javax.swing.JMenuItem jMenSalir;
    private javax.swing.JMenu jMenSalirSistema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuDepartamentos;
    private javax.swing.JMenuItem jMenuFolios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuMermas;
    private javax.swing.JMenuItem jMenuPerfiles;
    private javax.swing.JMenuItem jMenuProductos;
    private javax.swing.JMenuItem jMenuProveedores;
    private javax.swing.JMenu jMenuRecepcionCompras;
    private javax.swing.JMenu jMenuRegistroMermas;
    private javax.swing.JMenuItem jMenuUsuarios;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
