
package Presentacion;

import Controlador.Clientes;
import Controlador.Main;
import javax.swing.JOptionPane;

public class JIFClientesNuevo extends javax.swing.JInternalFrame {

    public JIFClientesNuevo() {
        initComponents();
        
        try {
            jChkActivo.setSelected(true);
            if(Clientes.ClienteNuevo==false){
                Clientes objCli = new Clientes(Clientes.IdCliente,"n", "n", "n", "n", "n", "n", 0);
                objCli.BuscaClienteId();
                jTxtId.setText(""+objCli.getId());
                jTxtRut.setText(""+objCli.getRut());
                jTxtNombre.setText(""+objCli.getNombre());
                jTxtDireccion.setText(""+objCli.getDireccion());
                jTxtCiudad.setText(""+objCli.getCiudad());
                jTxtComuna.setText(""+objCli.getComuna());
                jTxtGiro.setText(""+objCli.getGiro());
                boolean estado=true;
                if(objCli.getActivo()==0){
                    estado=false;
                }
                jChkActivo.setSelected(estado);
                jChkActivo.setEnabled(true);
            }else{
                jTxtId.setText("Automatico");
                jChkActivo.setEnabled(false);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jChkActivo = new javax.swing.JCheckBox();
        jTxtId = new javax.swing.JTextField();
        jTxtRut = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtDireccion = new javax.swing.JTextField();
        jTxtCiudad = new javax.swing.JTextField();
        jTxtComuna = new javax.swing.JTextField();
        jTxtGiro = new javax.swing.JTextField();
        jBtnGrabar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Id:");

        jLabel2.setText("RUT:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Ciudad:");

        jLabel6.setText("Comuna:");

        jLabel7.setText("Giro:");

        jChkActivo.setSelected(true);
        jChkActivo.setText("Activo");
        jChkActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkActivoActionPerformed(evt);
            }
        });

        jTxtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtId.setEnabled(false);

        jTxtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtRutFocusLost(evt);
            }
        });
        jTxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRutActionPerformed(evt);
            }
        });
        jTxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtRutKeyTyped(evt);
            }
        });
        jTxtRut.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTxtRutVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jChkActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtGiro)
                    .addComponent(jTxtDireccion)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jTxtRut, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jChkActivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnGrabar.setText("Grabar");
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGrabar)
                    .addComponent(jBtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
        try {
            if(jTxtRut.getText().isEmpty() || jTxtNombre.getText().isEmpty() || jTxtDireccion.getText().isEmpty() || jTxtCiudad.getText().isEmpty() || jTxtComuna.getText().isEmpty() || jTxtGiro.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos requeridos", "Clientes", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idCli=0;
            if(!Clientes.ClienteNuevo){
                idCli=Integer.parseInt( jTxtId.getText());
            }
            int cliAct=1;
            if(!jChkActivo.isSelected()){
                cliAct=0;
            }
            Clientes objCli = new Clientes(idCli, jTxtRut.getText(), jTxtNombre.getText(), jTxtDireccion.getText(), jTxtCiudad.getText(), jTxtComuna.getText(), jTxtGiro.getText(), cliAct);
            objCli.IprimeCliente();
            if(Clientes.ClienteNuevo){
                objCli.Grabar();
                jTxtRut.setText("");
                jTxtNombre.setText("");
                jTxtDireccion.setText("");
                jTxtCiudad.setText("");
                jTxtComuna.setText("");
                jTxtGiro.setText("");
                jTxtRut.requestFocus(true);
            }else{
                objCli.Actualizar();
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jBtnGrabarActionPerformed

    private void jChkActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkActivoActionPerformed

    private void jTxtRutVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTxtRutVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRutVetoableChange

    private void jTxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRutActionPerformed

    private void jTxtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtRutFocusLost
        try {
            if (Main.validarRut(jTxtRut.getText()) == false && !(jTxtRut.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Rut incorrecto, revise", "Error", JOptionPane.INFORMATION_MESSAGE);
                jBtnGrabar.setEnabled(false);
                return;
            }else{
                jBtnGrabar.setEnabled(true);
            }
            //VALIDO SI OTRO USUARIO TIENE MISMO RUT
            if(Clientes.ClienteNuevo==true){
                Clientes objCli = new Clientes(0,jTxtRut.getText(),"","","","","",0);
                objCli.ExisteRutCliente();
                if(Clientes.ExisteRUTCliente){
                    int msg=JOptionPane.showConfirmDialog(null, "Existe otro cliente con mismo rut, desae continuar", "Nuevo cliente", 0);
                    if(msg!=JOptionPane.YES_OPTION){
                        jTxtRut.setText(null);
                        jTxtRut.requestFocus();
                        return;
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtRutFocusLost

    private void jTxtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRutKeyTyped
        try {
            int Max=10;
            if(jTxtRut.getText().length()>=Max){
                evt.consume();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtRutKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JCheckBox jChkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCiudad;
    private javax.swing.JTextField jTxtComuna;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtGiro;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtRut;
    // End of variables declaration//GEN-END:variables
}
