
package Presentacion;

import Controlador.Folios;
import Controlador.LeeCAF;
import Controlador.Main;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class JIFFolios extends javax.swing.JInternalFrame {
    private int numeroTerminal;
    private String rutEmpresa;
    private String nombreEmpresa;
    private String nombreFantasiaEmpresa;
    

    public JIFFolios() {
        initComponents();
        Parametros();
        LeeDirectorio();
    }
    
    private void LeeDirectorio(){
        try {
            File dir = new File(System.getProperty("user.home")+File.separator+".local"+File.separator+"caf");
            String[] ficheros = dir.list();
            
            DefaultListModel modelo = new DefaultListModel();
            
            if (ficheros == null){
                System.out.println("No hay archivos en el directorio CAF");
            }else {
                jListArchivos.setModel(modelo);
                for (int i=0;i<ficheros.length;i++){
                    modelo.addElement(ficheros[i]);
                    //System.out.println(nombres_archivos[i]);
                }
            }
        } catch (Exception e) {
            System.err.println("Error LeeDirectorio: "+e);
        }   
    }
    
    private void Parametros(){
        try {
            Main objPar = new Main();
            objPar.parametos();
            numeroTerminal=objPar.getNumeroTerminal();
            nombreFantasiaEmpresa=objPar.getNombreFantasiaEmpresa();
            nombreEmpresa=objPar.getNombreEmpresa();
            rutEmpresa=objPar.getRutEmpresa();
            
            jLabelPanel.setText("Terminal:"+numeroTerminal+" Empresa: "+rutEmpresa+" - "+nombreFantasiaEmpresa);
            
        } catch (Exception e) {
            System.err.println("Error Parametros: "+e);
        }
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jTextDesde = new javax.swing.JTextField();
        jTextHasta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextDocumento = new javax.swing.JTextField();
        jTextRazonSocial = new javax.swing.JTextField();
        jTextRut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));
        jPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPanel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPanel.setText("Terminal:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabelPanel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPanel)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListArchivosMouseClicked(evt);
            }
        });
        jListArchivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListArchivosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListArchivos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Fecha:");

        jLabel2.setText("Folios desde:");

        jLabel3.setText("Documento:");

        jLabel4.setText("Razón Social:");

        jLabel5.setText("RUT");

        jTextFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFecha.setEnabled(false);

        jTextDesde.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDesde.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextDesde.setEnabled(false);

        jTextHasta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextHasta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextHasta.setEnabled(false);

        jLabel6.setText("Hasta:");

        jTextDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDocumento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextDocumento.setEnabled(false);

        jTextRazonSocial.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextRazonSocial.setEnabled(false);

        jTextRut.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextRut.setEnabled(false);

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextRazonSocial)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jTextFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListArchivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListArchivosKeyPressed
    }//GEN-LAST:event_jListArchivosKeyPressed

    private void jListArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListArchivosMouseClicked
        try {
            int i=jListArchivos.getSelectedIndex();
            if(i==-1){
                JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo!!!");
            }else{
                String nombreArchivo=jListArchivos.getSelectedValue();
                
                System.out.println("Archivo: "+nombreArchivo);
                System.out.println("RUT: "+rutEmpresa);
                
                LeeCAF objCAF = new LeeCAF(rutEmpresa, nombreArchivo);
                objCAF.LeeXML();
                
                jTextFecha.setText(objCAF.getFecha());
                jTextDesde.setText(""+objCAF.getrInicial());
                jTextHasta.setText(""+objCAF.getrFinal());
                jTextDocumento.setText(""+objCAF.getTipo());
                jTextRazonSocial.setText(objCAF.getRazonSocial());
                jTextRut.setText(objCAF.getRut());
            }
        } catch (Exception e) {
            System.err.println("Error jListArchivosMouseClicked: "+e);
        }
    }//GEN-LAST:event_jListArchivosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int i=jListArchivos.getSelectedIndex();
            if(i==-1){
                JOptionPane.showMessageDialog(null, "No hay un archivo seleccionado !!!");
                return;
            }

            if(jTextFecha.getText().isEmpty() || jTextRut.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Seleccione un archivo !!!");
            }else{
                //VALIDO QUE NO ESTE INGRESADO 
                Folios objFol = new Folios(Integer.parseInt(jTextDocumento.getText()),Integer.parseInt(jTextDesde.getText()),jTextFecha.getText(),Integer.parseInt(jTextDesde.getText()),Integer.parseInt(jTextHasta.getText()),jListArchivos.getSelectedValue());
                boolean ocupado = objFol.ExisteFolio();
                if(ocupado){
                    JOptionPane.showMessageDialog(null, "Folios ya ingresados");

                }else{
                    //Ingreso Folios
                    objFol.AgregarFolios();
                    JOptionPane.showMessageDialog(null, "Folios agregados !!!");
                    jTextDesde.setText(null);
                    jTextDocumento.setText(null);
                    jTextFecha.setText(null);
                    jTextHasta.setText(null);
                    jTextRazonSocial.setText(null);
                    jTextRut.setText(null);
                }
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPanel;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDesde;
    private javax.swing.JTextField jTextDocumento;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextHasta;
    private javax.swing.JTextField jTextRazonSocial;
    private javax.swing.JTextField jTextRut;
    // End of variables declaration//GEN-END:variables
}
