/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Main;
import Controlador.Mermas;
import Controlador.Precios;
import Controlador.Productos;
import Controlador.Usuarios;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aldo
 */
public class JIFMermas extends javax.swing.JInternalFrame {

    private String fecha;
    private String tipoCosto="U";
    private DefaultTableModel tabla;
    private String nombreColumnas [] ={"Plu","Nombre","Departamento","Costo","Cantidad","SubTotal"};
    private String datos [][] ={};
    
    
    public JIFMermas() {
        initComponents();
        LeeParametros();
        ContruyeTabla();
    }
    
    private void ContruyeTabla(){
        tabla=new DefaultTableModel(datos, nombreColumnas);
        jTableMerma.setModel(tabla);
    }
    
    private void BuscaProducto(){
        try {
            Productos objPro = new Productos(Integer.parseInt(jTxtPLU.getText()), 0, "", 0, 0, "", "", 0, "");
            objPro.ConsultaProductoId();
            if(!Productos.ProductoExiste){
                JOptionPane.showMessageDialog(null, "Producto no existe !!!");
                LimpiaDetalle();
                jTxtPLU.requestFocus();
            }else{
                jTxtNombre.setText(objPro.getNombre());
                jTxtDepartamento.setText(objPro.getDepartamento_nombre());
                //Busco Costo
                Precios objPre = new Precios(Integer.parseInt(jTxtPLU.getText()),0,0,0,0);
                objPre.DamePrecios_Margenes();
                if("U".equals(tipoCosto)){
                    jTxtCosto.setText(""+objPre.getUltimo_costo());
                }else{
                    jTxtCosto.setText(""+objPre.getCosto_pp());
                }
                jTxtCantidad.requestFocus();
            }
        } catch (HeadlessException | NumberFormatException e) {
            System.err.println("Error BuscaPproducto: "+e);
        }
    }
    
    private void Totaliza(){
        double tot=0;
        try {
            if(jTableMerma.getRowCount()>0){
                for(int i=0;i<jTableMerma.getRowCount();i++){
                    tot+=Double.parseDouble(jTableMerma.getValueAt(i, 5).toString());
                }
            }
            jTxtTotal.setText(""+tot);
        } catch (Exception e) {
        }
    }
    
    private void LimpiaDetalle(){
        jTxtPLU.setText(null);
        jTxtNombre.setText(null);
        jTxtDepartamento.setText(null);
        jTxtCosto.setText(null);
        jTxtCantidad.setText(null);
        jTxtSubTotal.setText(null);
    }
    
    private void LeeParametros(){
        try {
            Main objPar = new Main();
            objPar.parametos();
            tipoCosto=objPar.getTipoCosto();
            jTxtFecha.setText(objPar.getFecha());
            jTxtUsuario.setText(Usuarios.UsuarioIniciado);
            System.out.println("Tipo Costo: "+tipoCosto);
        } catch (Exception e) {
            System.err.println("Error LeeParametros: "+e);
        }
    }
    
    private void OK(){
        try {
            if(jTxtPLU.getText().isEmpty() || jTxtNombre.getText().isEmpty() || jTxtCosto.getText().isEmpty() || jTxtCantidad.getText().isEmpty() || jTxtSubTotal.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Faltan datos requeridos");
                jTxtPLU.requestFocus();
                return;
            }
            String plu=jTxtPLU.getText();
            String nombre=jTxtNombre.getText();
            String departamento=jTxtDepartamento.getText();
            String costo=jTxtCosto.getText();
            String cantidad=jTxtCantidad.getText();
            String subTotal=jTxtSubTotal.getText();
            String matriz[]={plu,nombre,departamento,costo,cantidad,subTotal};
            tabla.addRow(matriz);

            Totaliza();
            LimpiaDetalle();
            jTxtPLU.requestFocus();
        } catch (Exception e) {
            System.err.println("Error OK: "+e);
        }
    }
    
    private void LimpiaMerma(){
        int k=tabla.getRowCount();
        for(int j=0;j<k;j++){
            tabla.removeRow(0);
        }
        LimpiaDetalle();
        jTxtObservacion.setText(null);
        jTxtTotal.setText(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JTextField();
        jTxtUsuario = new javax.swing.JTextField();
        jTxtObservacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTxtPLU = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtDepartamento = new javax.swing.JTextField();
        jTxtCosto = new javax.swing.JTextField();
        jTxtCantidad = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBtnOK = new javax.swing.JButton();
        jBtnAyudaProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMerma = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jBtnGrabar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro de mermas");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Fecha");

        jLabel2.setText("Usuario");

        jLabel3.setText("Observación");

        jTxtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtFecha.setEnabled(false);

        jTxtUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtUsuario.setEnabled(false);

        jTxtObservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtObservacionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("PLU");

        jTxtPLU.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtPLU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtPLUFocusLost(evt);
            }
        });
        jTxtPLU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPLUKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPLUKeyPressed(evt);
            }
        });

        jTxtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtNombre.setEnabled(false);

        jTxtDepartamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtDepartamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtDepartamento.setEnabled(false);

        jTxtCosto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCosto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtCosto.setEnabled(false);

        jTxtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCantidadFocusLost(evt);
            }
        });
        jTxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCantidadKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCantidadKeyPressed(evt);
            }
        });

        jTxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSubTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxtSubTotal.setEnabled(false);

        jLabel5.setText("Nombre del producto");

        jLabel6.setText("Departamento");

        jLabel7.setText("Costo");

        jLabel8.setText("Cantidad");

        jLabel9.setText("Total");

        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });
        jBtnOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnOKKeyPressed(evt);
            }
        });

        jBtnAyudaProductos.setText("...");
        jBtnAyudaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAyudaProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxtPLU, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAyudaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxtNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAyudaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtPLU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnOK)))
                .addContainerGap())
        );

        jTableMerma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMerma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMermaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableMermaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMerma);

        jLabel10.setText("Total Merma:");

        jTxtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtTotal.setEnabled(false);

        jBtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save_2.png"))); // NOI18N
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir.png"))); // NOI18N
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnSalir)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnGrabar))
                    .addComponent(jBtnEliminar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAyudaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAyudaProductosActionPerformed
        // TODO add your handling code here:
        try {
            JDFAyudaProductos objAyu =new JDFAyudaProductos(null,true);
            objAyu.setVisible(true);
            
            int id=objAyu.getIdProducto();
            System.out.println(id);
            if(id!=0){
                jTxtPLU.setText(""+id);
                BuscaProducto();
            }else{
                jTxtPLU.setText(null);
                jTxtPLU.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBtnAyudaProductosActionPerformed

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        //Valido tengan datos
        OK();
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jTxtPLUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPLUFocusLost
        if(!jTxtPLU.getText().isEmpty()){
            BuscaProducto();
        }
    }//GEN-LAST:event_jTxtPLUFocusLost

    private void jTxtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCantidadFocusLost
        if(jTxtCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad");
        }else{
            
            try {
                //double cantidad=0;
                //cantidad=Double.parseDouble(jTxtCantidad.getText());
                //jTxtCantidad.setText(String.format("%.2f",cantidad));
                double subTotal =0;
                subTotal= (((Double.parseDouble(jTxtCantidad.getText()))*(Double.parseDouble(jTxtCosto.getText()))));
                jTxtSubTotal.setText(""+subTotal);
            } catch (Exception e) {
                jTxtSubTotal.setText("0");
                System.err.println("error jTxtCantidadFocusLost: "+e);
            }
        }
    }//GEN-LAST:event_jTxtCantidadFocusLost

    private void jTxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantidadKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) 
            && (caracter != KeyEvent.VK_BACK_SPACE)
            && (caracter != '.' || jTxtCantidad.getText().contains(".")) ) {evt.consume();} 
    }//GEN-LAST:event_jTxtCantidadKeyTyped

    private void jTxtPLUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPLUKeyTyped
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9'))) evt.consume();
    }//GEN-LAST:event_jTxtPLUKeyTyped

    private void jBtnOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnOKKeyPressed
        OK();
    }//GEN-LAST:event_jBtnOKKeyPressed

    private void jTableMermaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMermaMouseClicked
    }//GEN-LAST:event_jTableMermaMouseClicked

    private void jTableMermaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMermaMouseEntered
    }//GEN-LAST:event_jTableMermaMouseEntered

    private void jTxtObservacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtObservacionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTxtPLU.requestFocus();
        } 
    }//GEN-LAST:event_jTxtObservacionKeyPressed

    private void jTxtPLUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPLUKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Productos objPro = new Productos(Integer.parseInt(jTxtPLU.getText()), 0, "", 0, 0, "", "", 0, "");
            objPro.ConsultaProductoId();
            if(!Productos.ProductoExiste){
                JOptionPane.showMessageDialog(null, "Producto no existe");
            }else{
                jTxtCantidad.requestFocus();
            } 
        }
    }//GEN-LAST:event_jTxtPLUKeyPressed

    private void jTxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantidadKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jBtnOK.requestFocus();
        } 
    }//GEN-LAST:event_jTxtCantidadKeyPressed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=jTableMerma.getSelectedRow();
            if(i==-1){
                JOptionPane.showInternalMessageDialog(this, "Debe seleccionar un registro");
            }else{
                jTxtPLU.setText(String.valueOf(jTableMerma.getValueAt(i,0)));
                jTxtNombre.setText(String.valueOf(jTableMerma.getValueAt(i,1)));
                jTxtDepartamento.setText(String.valueOf(jTableMerma.getValueAt(i,2)));
                jTxtCosto.setText(String.valueOf(jTableMerma.getValueAt(i,3)));
                jTxtCantidad.setText(String.valueOf(jTableMerma.getValueAt(i,4)));
                jTxtSubTotal.setText(String.valueOf(jTableMerma.getValueAt(i,5)));
                tabla.removeRow(i);
                Totaliza();
                jTxtPLU.requestFocus();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        int i=jTableMerma.getSelectedRow();
        if(i==-1){
            JOptionPane.showInternalMessageDialog(this, "Debe seleccionar un registro");
        }else{
            int input = JOptionPane.showConfirmDialog(null, "Seguro de eliminar registro");
            if(input==0){
                tabla.removeRow(i);
                Totaliza();
                jTxtPLU.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
        try {
            if(jTxtFecha.getText().isEmpty() || jTxtObservacion.getText().isEmpty() || jTxtUsuario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Faltan datos requeridos");
                jTxtObservacion.requestFocus();
                return;
            }
            int i=jTableMerma.getRowCount();
            System.out.println("Filas: "+i);
            if(i==0){
                JOptionPane.showMessageDialog(null, "Debe agregar productos a mermar");
                jTxtPLU.requestFocus();
                return;
            }
            Mermas objMer = new Mermas( 0, jTxtFecha.getText(), jTxtUsuario.getText(), jTxtObservacion.getText(), tabla);
            objMer.Grabar();
            JOptionPane.showMessageDialog(null, "Merma grabada");

            LimpiaMerma();
            jTxtObservacion.requestFocus();
        } catch (Exception e) {
        }
            
        
        
    }//GEN-LAST:event_jBtnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAyudaProductos;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMerma;
    private javax.swing.JTextField jTxtCantidad;
    private javax.swing.JTextField jTxtCosto;
    private javax.swing.JTextField jTxtDepartamento;
    private javax.swing.JTextField jTxtFecha;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtObservacion;
    private javax.swing.JTextField jTxtPLU;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
