package Presentacion;

import Controlador.Clientes;
import Controlador.Departamentos;
import Controlador.Productos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class JIFProductosNuevo extends javax.swing.JInternalFrame {

    
    public JIFProductosNuevo() {
        initComponents();
        
        //Lleno combo departamentos
        try {
            Departamentos objDep = new Departamentos();
            ArrayList<Departamentos> objLis = new ArrayList<Departamentos>();
            objLis = objDep.Combo();
            for(int i=0; i<objLis.size() ;i++)
                jComboDepartamento.addItem(
                                   new Departamentos(
                                   objLis.get(i).getId(),
                                   objLis.get(i).getNombre()));
        } catch (Exception e) {
        }

        //Busco producto si es nuevo o editado
        try {
            if(Productos.ProductoNuevo==false){
                Productos objPro = new Productos (Productos.IdProducto, 0, "",0,0, "", "",0,"");
                objPro.ConsultaProductoId();
                jTxtId.setText(""+objPro.getId());
                jTxtNombre.setText(""+objPro.getNombre());
                jComboDepartamento.setSelectedIndex(objPro.getDep_id());
                jTxtStock.setText(""+objPro.getStock());
                jComboUnidades.setSelectedItem(""+objPro.getUnidad());
                jComboTipo.setSelectedItem(""+objPro.getTipo());
                jCheckAfecto.setSelected(true);
                if(objPro.getAfecto()==0){jCheckAfecto.setSelected(false);}
                jCheckActivo.setSelected(true);
                if(objPro.getActivo()==0){jCheckActivo.setSelected(false);}
            }else{
                jTxtId.setText("Automatico");
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckAfecto = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckActivo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        jTxtId = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jComboDepartamento = new javax.swing.JComboBox<>();
        jTxtStock = new javax.swing.JTextField();
        jComboUnidades = new javax.swing.JComboBox<>();
        jBtnGrabar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Productos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Id:");

        jLabel2.setText("Departamento:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Stock:");

        jCheckAfecto.setSelected(true);
        jCheckAfecto.setText("Afecto a IVA");
        jCheckAfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAfectoActionPerformed(evt);
            }
        });

        jLabel5.setText("Unidad:");

        jCheckActivo.setSelected(true);
        jCheckActivo.setText("Activo");

        jLabel6.setText("Tipo:");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unitario", "Pesable peso", "Pesable unidad" }));

        jTxtId.setEnabled(false);

        jTxtStock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtStock.setText("0");
        jTxtStock.setEnabled(false);

        jComboUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Un", "Kg", "Lt", "Mt", "Gr", "Cc", "Ml" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtNombre)
                            .addComponent(jComboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckAfecto)
                            .addComponent(jCheckActivo))
                        .addGap(356, 356, 356)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckAfecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckActivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnGrabar.setText("Grabar");
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGrabar)
                    .addComponent(jBtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckAfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAfectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckAfectoActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
        String unidad="";
        String tipo="";      
        int dep_id=0;
        int id=0;
        int afecto=1;
        int activo=1;
        
        try {
            if(Productos.ProductoNuevo==false) {id=Integer.parseInt(jTxtId.getText());}
            if(jComboDepartamento.getSelectedIndex()>0){dep_id=jComboDepartamento.getItemAt(jComboDepartamento.getSelectedIndex()).getId();}
            unidad=""+jComboUnidades.getSelectedItem();
            tipo=""+jComboTipo.getSelectedItem();
            if(!jCheckAfecto.isSelected()){afecto=0;}
            if(!jCheckActivo.isSelected()){activo=0;}

            if(jTxtNombre.getText().isEmpty() || dep_id==0 || unidad.isEmpty() || tipo.isEmpty()){
                JOptionPane.showMessageDialog(null, "Faltan datos requeridos del producto");
                return;
            }
            //int id, int dep_id, String nombre, double stock, int afecto, String unidad, String tipo, int activo
            Productos objPro = new Productos(id, dep_id, jTxtNombre.getText(), Double.parseDouble(jTxtStock.getText()),afecto, unidad, tipo, activo,"");
            if(Productos.ProductoNuevo){
                objPro.ConsultaProductoNombre();
                if(Productos.ProductoExiste){
                    JOptionPane.showMessageDialog(null, "Nombre del producto ya existe");
                    return;
                }
            }
            //Grabo/Actualizo
            if(Productos.ProductoNuevo){
                objPro.Grabar();
                jTxtNombre.setText(null);
                jComboDepartamento.setSelectedIndex(0);
                jComboUnidades.setSelectedIndex(0);
                jComboTipo.setSelectedIndex(0);
                jCheckAfecto.setSelected(true);
                jCheckActivo.setSelected(true);
                jTxtNombre.requestFocus();
            }else{
                objPro.Actualizar();
                this.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al grabar"+e);
        }
    }//GEN-LAST:event_jBtnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JCheckBox jCheckActivo;
    private javax.swing.JCheckBox jCheckAfecto;
    private javax.swing.JComboBox<Departamentos> jComboDepartamento;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JComboBox<String> jComboUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtStock;
    // End of variables declaration//GEN-END:variables
}
