/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Main;
import Controlador.Proveedores;
import javax.swing.JOptionPane;

/**
 *
 * @author aldo
 */
public class JIFProveedoresNuevo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFProveedoresNuevo
     */
    public JIFProveedoresNuevo() {
        initComponents();
        try {
            if(Proveedores.ProveedorNuevo==false){
                Proveedores objPro = new Proveedores(Proveedores.IdProveedor,"n", "n", "n", "n", "n", "n", "n", "n", "n");
                objPro.BuscaProveedorId();
                jTxtId.setText(""+objPro.getId());
                jTxtRut.setText(""+objPro.getRut());
                jTxtNombre.setText(""+objPro.getNombre());
                jTxtDireccion.setText(""+objPro.getDireccion());
                jTxtCiudad.setText(""+objPro.getCiudad());
                jTxtComuna.setText(""+objPro.getComuna());
                jTxtContacto.setText(""+objPro.getContacto());
                jTxtMail.setText(""+objPro.getMail());
                jTxtTelefono.setText(""+objPro.getTelefono());
                jTxtObservacion.setText(""+objPro.getObservacion());
            }else{
                jTxtId.setText("Automatico");
            }            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jTxtRut = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtDireccion = new javax.swing.JTextField();
        jTxtCiudad = new javax.swing.JTextField();
        jTxtComuna = new javax.swing.JTextField();
        jTxtContacto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtMail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtObservacion = new javax.swing.JTextField();
        jBtnGrabar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nuevo proveedor");

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Id:");

        jLabel2.setText("RUT:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Ciudad:");

        jLabel6.setText("Comuna:");

        jLabel7.setText("Contacto:");

        jTxtId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtId.setEnabled(false);

        jTxtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtRutFocusLost(evt);
            }
        });
        jTxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRutActionPerformed(evt);
            }
        });
        jTxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtRutKeyTyped(evt);
            }
        });
        jTxtRut.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTxtRutVetoableChange(evt);
            }
        });

        jTxtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContactoActionPerformed(evt);
            }
        });

        jLabel8.setText("Mail:");

        jLabel9.setText("Teléfono:");

        jLabel10.setText("Observación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMail)
                    .addComponent(jTxtContacto)
                    .addComponent(jTxtDireccion)
                    .addComponent(jTxtNombre)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtComuna, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jBtnGrabar.setText("Grabar");
        jBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGrabar)
                    .addComponent(jBtnSalir))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtRutFocusLost
        // TODO add your handling code here:
        //VALIDO QUE RUT SEA CORRECTO
        try {
            if (Main.validarRut(jTxtRut.getText()) == false && !(jTxtRut.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Rut incorrecto, revise", "Error", JOptionPane.INFORMATION_MESSAGE);
                jBtnGrabar.setEnabled(false);
                return;
            }else{
                jBtnGrabar.setEnabled(true);
            }
        } catch (Exception e) {
        }
        
        //VALIDO QUE RUT SEA UNICO
        try {
            if(Proveedores.ProveedorNuevo==true){
                Proveedores objPro = new Proveedores(0,jTxtRut.getText(),"n","n","","","","","","");
                objPro.ExisteRutCliente();
                if(objPro.ExisteRUTProveedor){
                    int msg=JOptionPane.showConfirmDialog(null, "Existe rut proveedor, desea repetirlo", "Nuevo proveedor",0);
                    if (msg!=JOptionPane.YES_OPTION){
                        jTxtRut.setText(null);
                        jTxtRut.requestFocus();
                        return;
                    }
                }
            }    
        } catch (Exception e) {
        } 
    }//GEN-LAST:event_jTxtRutFocusLost

    private void jTxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRutActionPerformed

    private void jTxtRutVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTxtRutVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRutVetoableChange

    private void jTxtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContactoActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGrabarActionPerformed
        // TODO add your handling code here:
        try {
            if(jTxtRut.getText().isEmpty() || jTxtNombre.getText().isEmpty() || jTxtDireccion.getText().isEmpty() || jTxtCiudad.getText().isEmpty() || jTxtComuna.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos requeridos", "Proveedores", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idPro=0;
            if(!Proveedores.ProveedorNuevo){
                idPro=Integer.parseInt( jTxtId.getText());
            }
            Proveedores objPro = new Proveedores(idPro, jTxtRut.getText(), jTxtNombre.getText(), jTxtDireccion.getText() ,   jTxtCiudad.getText(), jTxtComuna.getText(), jTxtContacto.getText(), jTxtMail.getText(), jTxtTelefono.getText(), jTxtObservacion.getText());
            
            if(Proveedores.ProveedorNuevo){
                objPro.Grabar();
                jTxtRut.setText(null);
                jTxtNombre.setText(null);
                jTxtDireccion.setText(null);
                jTxtCiudad.setText(null);
                jTxtComuna.setText(null);
                jTxtContacto.setText(null);
                jTxtMail.setText(null);
                jTxtTelefono.setText(null);
                jTxtObservacion.setText(null);
                jTxtRut.requestFocus(true);
            }else{
                objPro.Actualizar();
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jBtnGrabarActionPerformed

    private void jTxtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRutKeyTyped
        try {
            int Max=10;
            if(jTxtRut.getText().length()>=Max){
                evt.consume();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTxtRutKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGrabar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCiudad;
    private javax.swing.JTextField jTxtComuna;
    private javax.swing.JTextField jTxtContacto;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtMail;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtObservacion;
    private javax.swing.JTextField jTxtRut;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
